add_newline = true

format = """[$directory$git_branch$git_commit$git_status$git_state](bold magenta): """

[git_branch]
format = ":: [$branch(:$remote_branch)]($style) "

[git_commit]
format = ":: [$hash$tag]($style) "

[git_state]
format = "& [$state $progress_current/$progress_total)]($style) "

[git_status]
format = "[($all_status )($ahead_behind )]($style)"
